/**
 * External dependencies
 */
import React, { Component } from 'react';
import { connect } from 'react-redux';

/**
 * Internal dependencies
 */
import Card from 'components/card';
import { localize } from 'i18n-calypso';

class WaitingTwoFactorNotificationApproval extends Component {
	render() {
		return (
			<div>
				<form onSubmit={ this.onSubmitForm }>
					<Card className="is-compact">
						<p>
							{ this.props.translate( 'We just sent a push notification to your WordPress mobile app. ' +
								'Swipe or tap to open and verify your login.' ) }
						</p>
						<div>
							<img className="two-factor-authentication__auth-code-preview" src="/calypso/images/login/pushauth.svg" />
						</div>
						<p>
							{ this.props.translate( 'Or, type in the verification code generated by your Authenticator app' +
								' or sent via text.' ) }
						</p>
					</Card>
					<Card className="two-factor-authentication__form-action is-compact">
						<p>
							{ this.props.translate( 'Or, continue to your account using:' ) }
						</p>
						<p>
							<a href="#">{ this.props.translate( 'A recovery code via text' ) }</a>
						</p>
						<p>
							<a href="#">{ this.props.translate( 'An Authenticator application' ) }</a>
						</p>
					</Card>
				</form>
			</div>
		);
	}
}

export default connect( null, {} )( localize( WaitingTwoFactorNotificationApproval ) );
